### ISSUE TITLE
Missing performance_evaluation function

### ISSUE THREAD

**Issue by nizamibilal** [ChemPredict/CYP3A4-Time-dependent-Inhibition#1]
Hi,

Thanks for the nice paper and code!
I noticed that the file is missing from the repository as required in the following line. 

           from performance_evaluation import accuracy,recall,precision,AUC,bacc,aupr,f1,sensitivity,specificity,MCC,AllMetrics

Could you please update the code with missing file? I would like to try the code in my project. 

Thanks.

**Comment by ChemPredict** [comment]
Code for evaluation  updated.

Have to notice, the latest and complete codes suffered  a server crash, thus uploaded ones were written in hurry and need modification for running.
